language: java

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - development
    - immanual
    - josh
    - patrick
    - damian
    - charles

after_success:
  - mvn clean test jacoco:report coveralls:report
